algoritmo "Somar"
// Função :
// Autor : Stefane
// Data : 07/03/2023
// Seção de Declarações 
var
nome : caractere
n1, n2, soma : inteiro
inicio
// Seção de Comandos 
escreval("Olá, digite seu nome:")
leia(nome)
escreval ("Bem vindo!",nome)
escreval("Digite um número:")
leia(n1)
escreval("Digite outro número:")
leia(n2)
soma := n1 + n2
escreva ("A soma de ",n1, " e",n2," é ",soma)
//escreval("A soma dos números é :", soma)

fimalgoritmo
