algoritmo "Exercicio 04"
// Função :
// Autor :
// Data : 10/03/2023
// Seção de Declarações 
var

inicio
escreval("Reescreva as instruções abaixo com o mínimo de parênteses possível, mas sem alterar o resultado:")
escreval("a)6*5 ")
escreval("b)2+6*5 ")
escreval("c)2+3*6/(2+4)")
escreval("d)8/(3+1)*2")
escreval("e)2*(9-2)/14+3")
escreval("f)6/3+8/2")
escreval("g)(3+8/2)*4 + 3*2")
escreval("h)6*(3*3)+6 -10")
escreval("i)(10*8+3)*9")
escreval("j)-12*-4 +(3*-4)")
fimalgoritmo
