algoritmo "Exercicío 02"
// Função :
// Autor : Stefane
// Data : 10/03/2023
// Seção de Declarações 
var

inicio
escreval("Analise os algoritmos abaixo e diga o que será impresso na tela ao serem executados:")
escreval("a) A= 10 B= 5 ")
escreval("b) A= 30 B= 10 C= 40 ")
escreval("c) A= 10 B= 10 C= 10 ")
escreval("d) A= 12 B= 14 ")
escreval("e) A= 10 B= 20 C= 15 ")
escreval("f) X= 5  Y= 6  Z= 1 ")
fimalgoritmo
